import { Product, Testimonial, Category } from "@/types";

/* ═══════════════════════════════════════
   CATEGORIES
   ═══════════════════════════════════════ */

export const CATEGORIES: Category[] = [
  {
    name: "Anime",
    slug: "anime",
    image: "https://res.cloudinary.com/djxrvnb1c/image/upload/v1780470740/printala/products/poster-1780470737364.webp",
    count: 86,
    description: "Naruto, Demon Slayer, JJK, One Piece, DBZ & more",
  },
  {
    name: "Gaming",
    slug: "gaming",
    image: "https://res.cloudinary.com/djxrvnb1c/image/upload/v1780474521/printala/products/poster-1780474518756.webp",
    count: 52,
    description: "GTA, Valorant, God of War, BGMI, Minecraft",
  },
  {
    name: "Cricket",
    slug: "cricket",
    image: "https://res.cloudinary.com/djxrvnb1c/image/upload/v1780464101/printala/products/poster-1780464099932.webp",
    count: 44,
    description: "Dhoni, Kohli, Sachin, IPL, World Cup moments",
  },
  {
    name: "Cars & Bikes",
    slug: "cars",
    image: "https://res.cloudinary.com/djxrvnb1c/image/upload/v1780407470/printala/products/poster-1780407467955.webp",
    count: 48,
    description: "Supercars, JDM, Thar, Royal Enfield, F1",
  },
  {
    name: "Movies",
    slug: "bollywood",
    image: "https://res.cloudinary.com/djxrvnb1c/image/upload/v1780463780/printala/products/poster-1780463778437.webp",
    count: 38,
    description: "Iconic dialogues, retro Bollywood, KGF, Pushpa",
  },
  {
    name: "Football",
    slug: "football",
    image: "https://res.cloudinary.com/djxrvnb1c/image/upload/v1780473879/printala/products/poster-1780473877535.webp",
    count: 40,
    description: "Messi, Ronaldo, Mbappé, Champions League",
  },
  {
    name: "Anime Girls",
    slug: "anime-girls",
    image: "https://res.cloudinary.com/djxrvnb1c/image/upload/v1780470329/printala/products/poster-1780470326090.webp",
    count: 32,
    description: "Waifu posters, aesthetic anime art, zero two",
  },
  {
    name: "Split Posters",
    slug: "split-poster",
    image: "https://res.cloudinary.com/djxrvnb1c/image/upload/v1780473760/printala/products/poster-1780473758341.webp",
    count: 55,
    description: "3-panel & 5-panel sets for that full wall takeover",
  },
];

/* ═══════════════════════════════════════
   SIZES — INR
   ═══════════════════════════════════════ */

const REGULAR_SIZES: Product["sizes"] = [
  { label: "A4", dimensions: "21 × 29.7 cm", priceModifier: 0 },
  { label: "A3", dimensions: "29.7 × 42 cm", priceModifier: 100 },
  { label: "A2", dimensions: "42 × 59.4 cm", priceModifier: 250 },
  { label: "A1", dimensions: "59.4 × 84.1 cm", priceModifier: 450 },
];

const SPLIT_SIZES: Product["sizes"] = [
  { label: "Small", dimensions: "Each panel 20 × 40 cm", priceModifier: 0 },
  { label: "Medium", dimensions: "Each panel 30 × 60 cm", priceModifier: 400 },
  { label: "Large", dimensions: "Each panel 40 × 80 cm", priceModifier: 800 },
];

/* ═══════════════════════════════════════
   PRODUCTS — ALL ₹ PRICES
   ═══════════════════════════════════════ */

export const PRODUCTS: Product[] = [
  // ─── ANIME ───
  {
    _id: "anime-1",
    name: "Naruto Uzumaki — Sage Mode",
    slug: "naruto-sage-mode",
    description:
      "Dattebayo! The OG hokage-in-making in his legendary sage mode. Bold orange & black vibes. Every anime fan's room is incomplete without this. Premium 300gsm matte print — no cheap stuff here, bhai.",
    price: 199,
    comparePrice: 399,
    image: "https://res.cloudinary.com/djxrvnb1c/image/upload/v1780470740/printala/products/poster-1780470737364.webp",
    category: "anime",
    tags: ["naruto", "anime", "shonen", "hokage", "sage mode"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: true,
    bestseller: true,
    createdAt: "2024-01-15",
  },
  {
    _id: "anime-2",
    name: "Demon Slayer — Tanjiro Water Breathing",
    slug: "demon-slayer-tanjiro",
    description:
      "Tanjiro's Water Breathing First Form hits different on a wall. The blue water effects against dark background look insane in real life. Your hostel room just leveled up, senpai.",
    price: 199,
    image: "https://res.cloudinary.com/djxrvnb1c/image/upload/v1780470329/printala/products/poster-1780470326090.webp",
    category: "anime",
    tags: ["demon slayer", "tanjiro", "anime", "kimetsu no yaiba", "water breathing"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: true,
    bestseller: true,
    isNew: true,
    createdAt: "2024-03-01",
  },
  {
    _id: "anime-3",
    name: "One Piece — Straw Hat Nakama",
    slug: "one-piece-straw-hat",
    description:
      "The entire Straw Hat crew in one epic poster. Luffy's smile, Zoro's badassery, and the whole nakama energy. One Piece fans, your wall is calling.",
    price: 249,
    image: "https://res.cloudinary.com/djxrvnb1c/image/upload/v1780407470/printala/products/poster-1780407467955.webp",
    category: "anime",
    tags: ["one piece", "luffy", "zoro", "straw hat", "nakama"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: false,
    createdAt: "2024-02-10",
  },
  {
    _id: "anime-4",
    name: "Jujutsu Kaisen — Gojo Satoru",
    slug: "jjk-gojo-satoru",
    description:
      "The strongest sorcerer. Gojo's blindfold reveal moment in stunning detail. This poster radiates main character energy — perfect for your gaming setup or bedroom wall.",
    price: 199,
    image: "https://images.unsplash.com/photo-1541562232579-512a21360020?w=800&q=80",
    category: "anime",
    tags: ["jujutsu kaisen", "gojo", "jjk", "anime", "sorcerer"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: true,
    bestseller: true,
    createdAt: "2024-01-20",
  },
  {
    _id: "anime-5",
    name: "Dragon Ball Z — Ultra Instinct Goku",
    slug: "dbz-ultra-instinct",
    description:
      "Goku in Ultra Instinct form — the form that made every 90s kid lose their mind. Silver hair, calm eyes, absolute power. A must for every desi anime OG.",
    price: 199,
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
    category: "anime",
    tags: ["dragon ball z", "goku", "ultra instinct", "dbz", "saiyan"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: false,
    isNew: true,
    createdAt: "2024-03-18",
  },
  {
    _id: "anime-6",
    name: "Attack on Titan — Eren's Freedom",
    slug: "aot-eren-freedom",
    description:
      "Shinzou wo Sasageyo! Eren's transformation moment that broke the internet. Dark, dramatic, and absolutely fire. Your wall deserves this masterpiece.",
    price: 199,
    comparePrice: 349,
    image: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=800&q=80",
    category: "anime",
    tags: ["attack on titan", "eren", "aot", "titan", "freedom"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: true,
    createdAt: "2024-02-05",
  },

  // ─── GAMING ───
  {
    _id: "gaming-1",
    name: "GTA Vice City — Neon Retro",
    slug: "gta-vice-city-neon",
    description:
      "Tommy Vercetti vibes. The iconic Vice City neon skyline that every gamer grew up with. This poster hits nostalgia levels over 9000. Paisa vasool guaranteed.",
    price: 199,
    comparePrice: 349,
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
    category: "gaming",
    tags: ["gta", "vice city", "gaming", "retro", "neon"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: true,
    bestseller: true,
    createdAt: "2024-02-05",
  },
  {
    _id: "gaming-2",
    name: "Valorant — Jett & Phoenix",
    slug: "valorant-jett-phoenix",
    description:
      "Clutch or kick, bhai. Jett dashing and Phoenix flashing in a dynamic duo poster. Every Valorant player needs this next to their monitor. Rank push ke saath wall bhi push karo.",
    price: 199,
    image: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&q=80",
    category: "gaming",
    tags: ["valorant", "jett", "phoenix", "fps", "riot"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: false,
    isNew: true,
    createdAt: "2024-03-10",
  },
  {
    _id: "gaming-3",
    name: "God of War — Kratos & Atreus",
    slug: "god-of-war-kratos",
    description:
      "BOY! Kratos and Atreus in the Norse wilderness. The game that made grown men cry. This poster brings that same epic energy to your room. God-tier wall art.",
    price: 249,
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b2b28?w=800&q=80",
    category: "gaming",
    tags: ["god of war", "kratos", "atreus", "gaming", "playstation"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: true,
    bestseller: false,
    createdAt: "2024-01-28",
  },

  // ─── CRICKET ───
  {
    _id: "cricket-1",
    name: "Virat Kohli — King's Celebration",
    slug: "virat-kohli-celebration",
    description:
      "King Kohli in his aggressive celebration. The intensity, the passion, the fire — everything that makes Indian cricket fans go crazy. Ek dum jhakaas poster for every cricket lover!",
    price: 149,
    comparePrice: 299,
    image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80",
    category: "cricket",
    tags: ["virat kohli", "cricket", "india", "ipl", "rcb", "king"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: true,
    bestseller: true,
    createdAt: "2024-01-08",
  },
  {
    _id: "cricket-2",
    name: "MS Dhoni — Helicopter Shot",
    slug: "dhoni-helicopter-shot",
    description:
      "Thala for a reason! Captain Cool's legendary helicopter shot frozen in time. The shot that made Ranchi famous. Every CSK and India fan needs this on their wall. Whistle Podu! 🦁",
    price: 149,
    image: "https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?w=800&q=80",
    category: "cricket",
    tags: ["dhoni", "msd", "csk", "helicopter shot", "thala", "captain cool"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: true,
    bestseller: true,
    createdAt: "2024-02-01",
  },
  {
    _id: "cricket-3",
    name: "Sachin Tendulkar — God of Cricket",
    slug: "sachin-god-of-cricket",
    description:
      "The Master Blaster. Sachin's straight drive — the most beautiful shot in cricket history. 100 international centuries. 1 GOD. This poster is pure nostalgia for every Indian cricket fan.",
    price: 149,
    image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&q=80",
    category: "cricket",
    tags: ["sachin", "tendulkar", "god of cricket", "master blaster", "india"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: false,
    bestseller: true,
    createdAt: "2024-01-12",
  },
  {
    _id: "cricket-4",
    name: "World Cup 2011 — Dhoni's Winning Six",
    slug: "world-cup-2011-winning-six",
    description:
      "\"Dhoni finishes off in style! India lift the World Cup after 28 years!\" The moment that made 1.4 billion people cry happy tears. Wankhede erupting. Pure goosebumps. 🏆",
    price: 199,
    comparePrice: 349,
    image: "https://images.unsplash.com/photo-1587280501635-a19de238d1eb?w=800&q=80",
    category: "cricket",
    tags: ["world cup", "2011", "dhoni", "winning six", "india", "wankhede"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: true,
    isNew: true,
    createdAt: "2024-03-15",
  },

  // ─── CARS & BIKES ───
  {
    _id: "cars-1",
    name: "Lamborghini Aventador — Matte Black Beast",
    slug: "lamborghini-aventador-black",
    description:
      "The Aventador in matte black — every car lover's desktop wallpaper, now on your wall. Supercar dreams in poster form. Apni room ko garage feel do, bhai! 🔥",
    price: 199,
    comparePrice: 349,
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
    category: "cars",
    tags: ["lamborghini", "aventador", "supercar", "luxury", "black"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: true,
    bestseller: true,
    createdAt: "2024-01-25",
  },
  {
    _id: "cars-2",
    name: "Nissan GT-R R34 — Midnight Purple",
    slug: "gtr-r34-midnight-purple",
    description:
      "The Skyline GT-R R34 — the car that every JDM bro dreams about. Fast & Furious vibes. Paul Walker energy. Midnight Purple hits different on a wall.",
    price: 199,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
    category: "cars",
    tags: ["nissan", "gtr", "r34", "jdm", "skyline", "midnight purple"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: false,
    bestseller: true,
    createdAt: "2024-02-18",
  },
  {
    _id: "cars-3",
    name: "Mahindra Thar — Off-Road King",
    slug: "mahindra-thar-offroad",
    description:
      "The Thar in its natural habitat — mud, mountains, and pure desi engineering. India's favourite off-roader looking absolutely menacing. Perfect for every Thar lover's room! 🇮🇳",
    price: 149,
    image: "https://images.unsplash.com/photo-1614162118016-5c9b5b44b8b0?w=800&q=80",
    category: "cars",
    tags: ["thar", "mahindra", "offroad", "indian", "suv", "desi"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: false,
    isNew: true,
    createdAt: "2024-03-08",
  },
  {
    _id: "cars-4",
    name: "Royal Enfield Bullet — Classic 350",
    slug: "royal-enfield-bullet",
    description:
      "Dug-dug-dug. The sound that echoes through every Indian highway. The Bullet in all its glory against a mountain backdrop. Every RE rider's wall needs this. Ride karna, poster lagana. 🏍️",
    price: 149,
    image: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80",
    category: "cars",
    tags: ["royal enfield", "bullet", "classic", "motorcycle", "desi", "bike"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: false,
    bestseller: true,
    createdAt: "2024-01-30",
  },

  // ─── BOLLYWOOD ───
  {
    _id: "bollywood-1",
    name: "KGF — Rocky Bhai",
    slug: "kgf-rocky-bhai",
    description:
      "\"Violence... violence... violence.\" Rocky Bhai in his iconic gold mine scene. The poster that screams mass. Perfect for every KGF fan who thinks they're Rocky Bhai. Saalaam Rocky Bhai! 🔥",
    price: 199,
    comparePrice: 349,
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800&q=80",
    category: "bollywood",
    tags: ["kgf", "rocky bhai", "yash", "mass", "kannada", "bollywood"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: true,
    bestseller: true,
    createdAt: "2024-02-12",
  },
  {
    _id: "bollywood-2",
    name: "Pushpa — Jhukega Nahi",
    slug: "pushpa-jhukega-nahi",
    description:
      "\"Pushpa... naam sunke flower samajhta hai kya?\" Allu Arjun as Pushpa Raj in the most iconic pose of 2023. Srivalli playing in the background. Jhukega nahi sala! 🌿",
    price: 149,
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=80",
    category: "bollywood",
    tags: ["pushpa", "allu arjun", "jhukega nahi", "tollywood", "mass"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: false,
    bestseller: true,
    createdAt: "2024-01-18",
  },

  // ─── FOOTBALL ───
  {
    _id: "football-1",
    name: "Messi — World Cup Trophy Lift",
    slug: "messi-world-cup-trophy",
    description:
      "Leo Messi lifting the World Cup. The moment that settled the GOAT debate forever. Every football fan remembers where they were during that final. Messi supremacy poster for your wall. 🐐",
    price: 199,
    image: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80",
    category: "football",
    tags: ["messi", "world cup", "argentina", "goat", "football", "fifa"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: true,
    bestseller: true,
    createdAt: "2024-01-05",
  },
  {
    _id: "football-2",
    name: "Cristiano Ronaldo — SIUUUU",
    slug: "ronaldo-siuu-celebration",
    description:
      "SIUUUUUU! CR7 in his legendary celebration. The most copied celebration on every Indian football ground. Whether you're team Messi or CR7 — this poster is 🔥",
    price: 199,
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    category: "football",
    tags: ["ronaldo", "cr7", "siuu", "football", "portugal", "celebration"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: false,
    bestseller: true,
    createdAt: "2024-02-08",
  },

  // ─── ANIME GIRLS ───
  {
    _id: "animegirl-1",
    name: "Zero Two — Darling in the Franxx",
    slug: "zero-two-darling",
    description:
      "Darling~ Zero Two in her iconic cherry blossom scene. The ultimate waifu poster for your room. Aesthetic anime art that looks gorgeous on any wall. Your room's about to go full weeb mode. 💕",
    price: 199,
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    category: "anime-girls",
    tags: ["zero two", "darling in the franxx", "waifu", "anime girl", "aesthetic"],
    sizes: REGULAR_SIZES,
    type: "poster",
    inStock: true,
    featured: false,
    bestseller: true,
    isNew: true,
    createdAt: "2024-03-12",
  },

  // ─── SPLIT POSTERS ───
  {
    _id: "split-1",
    name: "Himalayan Sunrise — 5 Panel Split",
    slug: "himalayan-sunrise-5-panel",
    description:
      "The mighty Himalayas at golden hour, spanning 5 panels. Transform your drawing room wall into a window to the mountains. Mummy bhi impress, dost bhi impress. Sab khush! 🏔️",
    price: 999,
    comparePrice: 1799,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    category: "split-poster",
    tags: ["split poster", "5 panel", "himalaya", "mountain", "sunrise", "india"],
    sizes: SPLIT_SIZES,
    type: "split-poster",
    panels: 5,
    inStock: true,
    featured: true,
    bestseller: true,
    createdAt: "2024-01-18",
  },
  {
    _id: "split-2",
    name: "Mumbai Skyline Night — 3 Panel Split",
    slug: "mumbai-skyline-3-panel",
    description:
      "Maximum City at midnight! Mumbai's stunning skyline with Marine Drive lights, split across 3 panels. The city that never sleeps, now on your wall. Aamchi Mumbai! 🌃",
    price: 799,
    comparePrice: 1299,
    image: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&q=80",
    category: "split-poster",
    tags: ["split poster", "3 panel", "mumbai", "skyline", "night", "marine drive"],
    sizes: SPLIT_SIZES,
    type: "split-poster",
    panels: 3,
    inStock: true,
    featured: true,
    bestseller: true,
    createdAt: "2024-02-12",
  },
  {
    _id: "split-3",
    name: "Anime Battle Scene — 5 Panel Split",
    slug: "anime-battle-5-panel",
    description:
      "An epic anime battle scene spanning your entire wall. 5 panels of pure action — explosions, energy blasts, and main character energy. Your room is basically an anime now. Sugoi! ⚡",
    price: 1199,
    comparePrice: 1999,
    image: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&q=80",
    category: "split-poster",
    tags: ["split poster", "5 panel", "anime", "action", "battle"],
    sizes: SPLIT_SIZES,
    type: "split-poster",
    panels: 5,
    inStock: true,
    featured: true,
    bestseller: false,
    isNew: true,
    createdAt: "2024-03-15",
  },
  {
    _id: "split-4",
    name: "Goa Beach Sunset — 3 Panel Split",
    slug: "goa-sunset-3-panel",
    description:
      "Goan sunset vibes across 3 panels. Palm trees, orange sky, calm waves — Goa ka feeling ghar mein. Perfect for your living room or that accent wall you've been planning. 🌴",
    price: 799,
    image: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&q=80",
    category: "split-poster",
    tags: ["split poster", "3 panel", "goa", "beach", "sunset", "india"],
    sizes: SPLIT_SIZES,
    type: "split-poster",
    panels: 3,
    inStock: true,
    featured: false,
    createdAt: "2024-02-25",
  },
  {
    _id: "split-5",
    name: "Northern Lights — 5 Panel Split",
    slug: "northern-lights-5-panel",
    description:
      "Aurora Borealis dancing across the Arctic sky. Greens, purples, and blues spanning 5 panels. Basically Ladakh at night but make it extra. Your wall, but make it cosmic. 🌌",
    price: 1099,
    image: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=800&q=80",
    category: "split-poster",
    tags: ["split poster", "5 panel", "aurora", "northern lights", "cosmic"],
    sizes: SPLIT_SIZES,
    type: "split-poster",
    panels: 5,
    inStock: true,
    featured: false,
    createdAt: "2024-01-28",
  },
  {
    _id: "split-6",
    name: "Supercar Collection — 3 Panel Split",
    slug: "supercar-garage-3-panel",
    description:
      "Dream garage goals across 3 panels. Lambos, Ferraris, and GT-Rs all in one frame. Apna time aayega — tab tak poster se kaam chalao! 🏎️",
    price: 899,
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
    category: "split-poster",
    tags: ["split poster", "3 panel", "supercar", "garage", "luxury"],
    sizes: SPLIT_SIZES,
    type: "split-poster",
    panels: 3,
    inStock: true,
    featured: false,
    isNew: true,
    createdAt: "2024-03-20",
  },
];

/* ═══════════════════════════════════════
   TESTIMONIALS — INDIAN CUSTOMERS
   ═══════════════════════════════════════ */

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Arjun Sharma",
    location: "Delhi, India",
    text: "Bhai kya mast quality hai! Naruto aur JJK poster liya — 300gsm paper ekdum solid feel hota hai. Hostel room pura anime setup ban gaya. 10/10 recommend karta hoon. 🔥",
    rating: 5,
    avatar: "AS",
  },
  {
    id: "2",
    name: "Priya Nair",
    location: "Bangalore, India",
    text: "The 5-panel Himalayan split poster is STUNNING. Mere drawing room mein laga hai and everyone who visits asks where I got it. Packaging bhi solid tha — no creases at all!",
    rating: 5,
    avatar: "PN",
  },
  {
    id: "3",
    name: "Rohit Patel",
    location: "Mumbai, India",
    text: "Dhoni helicopter shot poster + Kohli celebration = my room is now a cricket museum! ₹149 mein itni quality? Paisa vasool. Already ordering more for my friends.",
    rating: 5,
    avatar: "RP",
  },
  {
    id: "4",
    name: "Sneha Reddy",
    location: "Hyderabad, India",
    text: "Got the KGF Rocky Bhai and Zero Two posters — my room has both mass AND class now 😂 Paper quality is genuinely premium, not like those ₹50 wale cheap posters. Worth every rupee!",
    rating: 5,
    avatar: "SR",
  },
  {
    id: "5",
    name: "Karthik Menon",
    location: "Chennai, India",
    text: "Ordered 8 posters — anime, cars, cricket sab kuch. Tube packaging mein aaya, ekdum flat and perfect. 4 din mein deliver ho gaya. Dost log jealous ho gaye. Best poster shop in India! 💪",
    rating: 5,
    avatar: "KM",
  },
  {
    id: "6",
    name: "Aisha Khan",
    location: "Pune, India",
    text: "Boyfriend ke birthday pe 3-panel Mumbai skyline split poster gift kiya — he literally screamed! The quality is so good, it looks like a canvas painting. Printala is my go-to now. ❤️",
    rating: 5,
    avatar: "AK",
  },
];